In [12]:
import pandas as pd 
import yfinance as yf
import matplotlib.pyplot as plt 
pd.options.display.float_format = '{:.4f}'.format
plt.style.use("seaborn")

In [2]:
start = "2014-10-01"
end = "2021-05-31"

In [10]:
symbol = ["BA", "MSFT", "^DJI", "EURUSD=X", "GC=F", "BTC-USD"]

In [11]:
df = yf.download(symbol, start, end)
df

[*********************100%***********************]  6 of 6 completed

             Adj Close                                                   \
                    BA       BTC-USD  EURUSD=X         GC=F        MSFT
Date
2014-09-30  110.763153    386.944000  1.269084  1210.500000   40.585476
2014-10-01  108.406677    383.614990  1.262834  1214.599976   40.182781
2014-10-02  107.971893    375.071991  1.262419  1214.199951   40.060207
2014-10-03  109.876213    359.511993  1.267058  1192.199951   40.349106
2014-10-04         NaN    328.865997       NaN          NaN         NaN
...                ...           ...       ...          ...         ...
2021-05-26  241.369995  39294.199219  1.224909  1901.300049  250.551086
2021-05-27  250.699997  38436.968750  1.219260  1895.699951  248.379227
2021-05-28  247.020004  35697.605469  1.219319  1902.500000  248.747833
2021-05-29         NaN  34616.066406       NaN          NaN         NaN
2021-05-30         NaN  35678.128906       NaN          NaN         NaN

                               Close                                       \
                    ^DJI          BA       BTC-USD  EURUSD=X         GC=F
Date
2014-09-30  17042.900391  127.379997    386.944000  1.269084  1210.500000
2014-10-01  16804.710938  124.669998    383.614990  1.262834  1214.599976
2014-10-02  16801.050781  124.169998    375.071991  1.262419  1214.199951
2014-10-03  17009.689453  126.360001    359.511993  1.267058  1192.199951
2014-10-04           NaN         NaN    328.865997       NaN          NaN
...                  ...         ...           ...       ...          ...
2021-05-26  34323.050781  241.369995  39294.199219  1.224909  1901.300049
2021-05-27  34464.640625  250.699997  38436.968750  1.219260  1895.699951
2021-05-28  34529.449219  247.020004  35697.605469  1.219319  1902.500000
2021-05-29           NaN         NaN  34616.066406       NaN          NaN
2021-05-30           NaN         NaN  35678.128906       NaN          NaN

            ...      Open                                             Volume  \
            ...  EURUSD=X         GC=F        MSFT          ^DJI          BA
Date        ...
2014-09-30  ...  1.269100  1214.800049   46.369999  17070.449219   4000200.0
2014-10-01  ...  1.262913  1207.699951   46.270000  17040.460938   5265200.0
2014-10-02  ...  1.262499  1215.300049   45.830002  16808.269531   3204500.0
2014-10-03  ...  1.266994  1212.400024   45.980000  16802.199219   3075900.0
2014-10-04  ...       NaN          NaN         NaN           NaN         NaN
...         ...       ...          ...         ...           ...         ...
2021-05-26  ...  1.224890  1901.300049  251.429993  34336.339844   7240200.0
2021-05-27  ...  1.219036  1896.800049  251.169998  34432.468750  18404400.0
2021-05-28  ...  1.219274  1897.500000  251.000000  34558.500000  11197400.0
2021-05-29  ...       NaN          NaN         NaN           NaN         NaN
2021-05-30  ...       NaN          NaN         NaN           NaN         NaN


                 BTC-USD EURUSD=X      GC=F        MSFT         ^DJI
Date
2014-09-30  3.470730e+07      0.0     680.0  33033100.0  102290000.0
2014-10-01  2.622940e+07      0.0     178.0  38088400.0  104240000.0
2014-10-02  2.177770e+07      0.0     176.0  25119400.0   75490000.0
2014-10-03  3.090120e+07      0.0     499.0  32453200.0   87940000.0
2014-10-04  4.723650e+07      NaN       NaN         NaN          NaN
...                  ...      ...       ...         ...          ...
2021-05-26  5.134674e+10      0.0  170526.0  17771600.0  258780000.0
2021-05-27  4.321097e+10      0.0   35794.0  24426200.0  520630000.0
2021-05-28  5.520019e+10      0.0    2415.0  18270200.0  290850000.0
2021-05-29  4.523101e+10      NaN       NaN         NaN          NaN
2021-05-30  3.164608e+10      NaN       NaN         NaN          NaN

[2435 rows x 36 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1678 entries, 2014-09-30 to 2021-05-28
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       1678 non-null   float64
 1   High       1678 non-null   float64
 2   Low        1678 non-null   float64
 3   Close      1678 non-null   float64
 4   Adj Close  1678 non-null   float64
 5   Volume     1678 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 91.8 KB

In [14]:
df

           Adj Close                                                    \
                  BA    BTC-USD EURUSD=X      GC=F     MSFT       ^DJI
Date
2014-09-30  110.7632   386.9440   1.2691 1210.5000  40.5855 17042.9004
2014-10-01  108.4067   383.6150   1.2628 1214.6000  40.1828 16804.7109
2014-10-02  107.9719   375.0720   1.2624 1214.2000  40.0602 16801.0508
2014-10-03  109.8762   359.5120   1.2671 1192.2000  40.3491 17009.6895
2014-10-04       NaN   328.8660      NaN       NaN      NaN        NaN
...              ...        ...      ...       ...      ...        ...
2021-05-26  241.3700 39294.1992   1.2249 1901.3000 250.5511 34323.0508
2021-05-27  250.7000 38436.9688   1.2193 1895.7000 248.3792 34464.6406
2021-05-28  247.0200 35697.6055   1.2193 1902.5000 248.7478 34529.4492
2021-05-29       NaN 34616.0664      NaN       NaN      NaN        NaN
2021-05-30       NaN 35678.1289      NaN       NaN      NaN        NaN

              Close                                ...     Open            \
                 BA    BTC-USD EURUSD=X      GC=F  ... EURUSD=X      GC=F
Date                                               ...
2014-09-30 127.3800   386.9440   1.2691 1210.5000  ...   1.2691 1214.8000
2014-10-01 124.6700   383.6150   1.2628 1214.6000  ...   1.2629 1207.7000
2014-10-02 124.1700   375.0720   1.2624 1214.2000  ...   1.2625 1215.3000
2014-10-03 126.3600   359.5120   1.2671 1192.2000  ...   1.2670 1212.4000
2014-10-04      NaN   328.8660      NaN       NaN  ...      NaN       NaN
...             ...        ...      ...       ...  ...      ...       ...
2021-05-26 241.3700 39294.1992   1.2249 1901.3000  ...   1.2249 1901.3000
2021-05-27 250.7000 38436.9688   1.2193 1895.7000  ...   1.2190 1896.8000
2021-05-28 247.0200 35697.6055   1.2193 1902.5000  ...   1.2193 1897.5000
2021-05-29      NaN 34616.0664      NaN       NaN  ...      NaN       NaN
2021-05-30      NaN 35678.1289      NaN       NaN  ...      NaN       NaN

                                      Volume                            \
               MSFT       ^DJI            BA          BTC-USD EURUSD=X
Date
2014-09-30  46.3700 17070.4492  4000200.0000    34707300.0000   0.0000
2014-10-01  46.2700 17040.4609  5265200.0000    26229400.0000   0.0000
2014-10-02  45.8300 16808.2695  3204500.0000    21777700.0000   0.0000
2014-10-03  45.9800 16802.1992  3075900.0000    30901200.0000   0.0000
2014-10-04      NaN        NaN           NaN    47236500.0000      NaN
...             ...        ...           ...              ...      ...
2021-05-26 251.4300 34336.3398  7240200.0000 51346735160.0000   0.0000
2021-05-27 251.1700 34432.4688 18404400.0000 43210968721.0000   0.0000
2021-05-28 251.0000 34558.5000 11197400.0000 55200191952.0000   0.0000
2021-05-29      NaN        NaN           NaN 45231013335.0000      NaN
2021-05-30      NaN        NaN           NaN 31646080921.0000      NaN


                  GC=F          MSFT           ^DJI
Date
2014-09-30    680.0000 33033100.0000 102290000.0000
2014-10-01    178.0000 38088400.0000 104240000.0000
2014-10-02    176.0000 25119400.0000  75490000.0000
2014-10-03    499.0000 32453200.0000  87940000.0000
2014-10-04         NaN           NaN            NaN
...                ...           ...            ...
2021-05-26 170526.0000 17771600.0000 258780000.0000
2021-05-27  35794.0000 24426200.0000 520630000.0000
2021-05-28   2415.0000 18270200.0000 290850000.0000
2021-05-29         NaN           NaN            NaN
2021-05-30         NaN           NaN            NaN

[2435 rows x 36 columns]